### ISSUE TITLE
Try to make something more complicated.

### ISSUE THREAD

**Issue by lazyprop** [Algomaster1120/FactorialRecursion#1]
As you know that Python is very lenient with data types. So, you can store very big numbers in the Int type. Try to improve your program so that it does not take advantage of its leniency and only store 32 bits (9 digits) of data.

**Comment by Algomaster0628** [comment]
It is the fastest possible way.Well on what are you working nowdays.You should learn React native.It will let you make Apps that work on mobile and also as you already know making web apps  so it will be easy for you.
